# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1568090952);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1568091072);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1568094192);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1568090832);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1568090712);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1568091192);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1568094077486");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1568097677486");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160414065608");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20160414065608");
user_pref("browser.startup.homepage_override.mstone", "45.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\"]},\"seen\":[\"loop-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"PanelUI-contents\"],\"currentVersion\":5,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1567846794684");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1567760457923");
user_pref("datareporting.policy.firstRunTime", "1567760394684");
user_pref("datareporting.sessions.current.activeTicks", 29);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 5481);
user_pref("datareporting.sessions.current.main", 759);
user_pref("datareporting.sessions.current.sessionRestored", 5529);
user_pref("datareporting.sessions.current.startTime", "1568090468303");
user_pref("datareporting.sessions.current.totalTime", 5801);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1567760391308,\"a\":188,\"t\":80747,\"c\":true,\"m\":667,\"fp\":6724,\"sr\":6551}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1567841140768,\"a\":10,\"t\":58,\"c\":true,\"m\":371,\"fp\":4878,\"sr\":4154}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1567843301574,\"a\":4,\"t\":160202,\"c\":true,\"m\":90,\"fp\":3050,\"sr\":2078}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1568020636614,\"a\":4,\"t\":23,\"c\":true,\"m\":340,\"fp\":5138,\"sr\":4145}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"45.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"45.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.0.2");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.0.2");
user_pref("extensions.lastPlatformVersion", "45.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1460620815000}},\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"45.0.2\",\"st\":1460621438000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"45.0.2\",\"st\":1460621437000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.0.2\",\"st\":1460620814000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":false,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("gecko.buildID", "20160414065608");
user_pref("gecko.mstone", "45.0.2");
user_pref("idle.lastDailyNotification", 1568090585);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1567760459);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20160414065608");
user_pref("media.gmp-manager.lastCheck", 1568090534);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1567761368);
user_pref("places.history.expiration.transient_current_max_pages", 26203);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1567761368);
user_pref("toolkit.startup.last_success", 1568090469);
user_pref("toolkit.telemetry.cachedClientID", "61c802fa-e66c-40e5-beae-c75234ef93fa");
user_pref("toolkit.telemetry.previousBuildID", "20160414065608");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
